//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKDManager.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Member
    {
        public int MemberID { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public Nullable<System.DateTime> BirthDate { get; set; }
        public int Gender { get; set; }
        public string Address1 { get; set; }
        public string Address2 { get; set; }
        public string NPA { get; set; }
        public string Town { get; set; }
        public string Email { get; set; }
        public string HomePhoneNb { get; set; }
        public string WorkPhoneNb { get; set; }
        public string MobilePhoneNb { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> EndDate { get; set; }
        public Nullable<int> BeltID { get; set; }
        public int ClubID { get; set; }
        public int FeeID { get; set; }
        public string ResponsiblePerson { get; set; }
        public Nullable<int> AnnualLicensePaidUntil { get; set; }
    }
}
