//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TKDManager.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class TKDManagerEntities : DbContext
    {
        public TKDManagerEntities()
            : base("name=TKDManagerEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Belt> Belt { get; set; }
        public virtual DbSet<Bill> Bill { get; set; }
        public virtual DbSet<Club> Club { get; set; }
        public virtual DbSet<Fee> Fee { get; set; }
        public virtual DbSet<Member> Member { get; set; }
    }
}
